a = input("Enter Your name :")
b = int(input("Enter Your age :"))
c = float(input("Enter Your height :"))
print("Your name is", a)
print("Your age is", b)
print("Your height is", c)
print("Your name is {} and your age is {} and your height is {}".format(a, b, c))
print(f"Your name is {a} and your age is {b} and your height is {c}")
print("Your name is %s and your age is %d and your height is %.2f" % (a, b, c))
print("Your name is {0} and your age is {1} and your height is {2}".format(a, b, c))